### ISSUE TITLE
Просто запустил пример из описания про ежика

### ISSUE THREAD

**Issue by PopkovS** [Den4ikAI/ruaccent#1]
D:\projects\test\venv\Scripts\python.exe D:/projects/test/main.py
Fetching 54 files: 100%|██████████| 54/54 [00:01<00:00, 39.62it/s]
Traceback (most recent call last):
  File "D:\projects\test\main.py", line 5, in <module>
    accentizer.load(omograph_model_size='medium', dict_load_startup=False)
  File "D:\projects\test\venv\lib\site-packages\ruaccent\ruaccent.py", line 18, in load
    self.omographs = json.load(open(self.workdir + '/dictionary/omographs.json'))
  File "C:\python3.10.4\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\python3.10.4\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1159357: character maps to <undefined>

**Comment by PopkovS** [comment]
\venv\Lib\site-packages\ruaccent\ruaccent.py

self.omographs = json.load(open(self.workdir + '/dictionary/omographs.json', encoding='utf-8'))
Дописал encoding, вроде работает(причем круто)

**Comment by Den4ikAI** [comment]
Такая проблема только у винды. Исправил
