### ISSUE TITLE
Как работать с custom_homographs?

### ISSUE THREAD

**Issue by LecronRu** [Den4ikAI/ruaccent#5]
```python
accentizer.load(omograph_model_size='big', custom_homographs = {'опер': ['+oпер', 'oп+ёр']})
text = 'Подойдя к стене, опер поставил на ней крест. Подойдя к стене, опер на неё свою ношу. Там были опер и следак. На задержание выехал старший опер.'
# process_omo это как process_all, только без расстановки ударений
accentizer.process_omo(text)
# 'подойдя к стене, +oпер поставил на ней крест. подойдя к стене, +oпер на неё свою ношу. там были oп+ёр и следак. на задержание выехал старший oп+ёр.'
```
Меняем порядок следования форм...
```python
accentizer.load(omograph_model_size='big', custom_homographs = {'опер': ['oп+ёр', '+oпер']})
accentizer.process_omo(text)
# 'подойдя к стене, +oпер поставил на ней крест. подойдя к стене, +oпер на неё свою ношу. там были oп+ёр и следак. на задержание выехал старший oп+ёр.'
```
...на результат не влияет. Складывается ощущение, что.... магия. Но для магии слишком много ошибок — 3 из 4

Решил проверить известные программе омографы. Случайно обнаружил, что для "лету" указаны не все формы. Переопределяем.
```python
text = 'Нам ещё несколько часов лету. К лету купим. Он ловил мух на лету.'
accentizer.load(omograph_model_size='big', custom_homographs = {'лету': ['л+ету', 'лет+у', 'л+ёту']})
accentizer.process_omo(text)
# 'нам ещё несколько часов л+ету. к л+ету купим. он ловил мух на лет+у.'
```
Меняем порядок следования форм...
```python
accentizer.load(omograph_model_size='big', custom_homographs = {'лету': ['л+ёту', 'л+ету', 'лет+у']})
accentizer.process_omo(text)
'нам ещё несколько часов л+ёту. к л+ёту купим. он ловил мух на лет+у.'
```
...влияет на результат. В разрешении участвует третья, ранее неизвестная форма.

Поэтому прошу пояснить, как работать с custom_homographs? В каком порядке указывать варианты? Иногда это влияет на результат, иногда нет. Как технически можно разрешить омограф, о котором раньше не знали, что он омограф? Ладно еще кластеризовать, но как выбрать кластерам соответсвующий вариант формы?

**Comment by Den4ikAI** [comment]
Привет, Я ожидал, что модель генерализуется на омографы, но этого не произошло. Функцию выпилю в следующем релизе (а он будет ближе к пятнице)
