### ISSUE TITLE
accentizer.process_all Падает на некоторых словах

### ISSUE THREAD

**Issue by SazerLife** [Den4ikAI/ruaccent#7]
Привет! Спасибо за твою работу! 

Заметил, что на некотрых словах процесс расстановки может падать. По видимому какая-то обработка внутри пораждает непредвиденные None-ы.

Напирмер, `accentizer.process_all("питье")` вернёт:

```
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 accentizer.process_all(\"питье\")

File miniconda3/envs/py-3.10/lib/python3.10/site-packages/ruaccent/ruaccent.py:228, in RUAccent.process_all(self, text)
    226 if len(accented_tokens) == len(text):
    227     for i in range(len(text)):
--> 228         if '+' in accented_tokens[i]:
    229             text[i] = accented_tokens[i]
    230 stress_usages = self.extract_entities(self.stress_usage_predictor.predict_stress_usage(sentence))

TypeError: argument of type 'NoneType' is not iterable"
}
```

System: Linux (Ubuntu)
Python: 3.10.13

**Comment by SazerLife** [comment]
@Den4ikAI Иногда такая же ошибка падает для слов в контексте. Например, здесь все слова по отдельности обрабатываются, а вместе получается ошибка.

`accentizer.process_all("мы ели и пили с удовольствием")`

**Comment by SazerLife** [comment]
Инициализация была такая
```python
accentizer = RUAccent()
accentizer.load(omograph_model_size='turbo', use_dictionary=False, device="CPU", workdir=None)
```

**Comment by Den4ikAI** [comment]
@SazerLife Привет, благодарю за фидбек, только сейчас руки дошли поправить. Для решения проблемы, просто обнови ruaccent.
